services:
  web:
    image: johnverz7/laravel-app:latest
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  
  db:
    platform: "linux/amd64"
    image: mysql:8.0
    # env_file:
    #   - .env
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 1234
    command: --bind-address=0.0.0.0
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: