name: Build and deploy Laravel app to Azure Web App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: mylaravelapp        # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'         # Path to your Laravel project
  PHP_VERSION: '8.2'                     # PHP version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, pdo, bcmath, intl

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Build front-end assets
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: |
          npm install
          npm run build --production

       # Create a compressed archive (tar.gz) of the application files
      - name: Create archive of Laravel app
        run: |
          tar -czf laravel-app.tar.gz --exclude=node_modules --exclude=vendor --exclude=.git .
          echo "Created a tar.gz archive of the application."

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: laravel-app
          path: laravel-app.tar.gz

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: laravel-app
        
      # Unzip the tar.gz archive before deployment
      - name: Extract the archive
        run: |
          tar -xzf laravel-app.tar.gz
          echo "Extracted the tar.gz archive."

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      - name: Modify config/database.php to use Azure env variables
        run: |
          # Replace DB settings in config/database.php with Azure environment variables
          sed -i "s|DB_CONNECTION', 'sqlite'|DB_CONNECTION', 'mysql'|g" config/database.php
          # Replace DB_HOST with AZURE_MYSQL_HOST for the MySQL configuration section
          sed -i '/\'mysql\' => \[/,/\],/s|DB_HOST|AZURE_MYSQL_HOST|g' config/database.php
          # Replace DB_PORT with AZURE_MYSQL_PORT for the MySQL configuration section
          sed -i '/\'mysql\' => \[/,/\],/s|DB_PORT|AZURE_MYSQL_PORT|g' config/database.php
          # Replace DB_DATABASE with AZURE_MYSQL_DBNAME for the MySQL configuration section
          sed -i '/\'mysql\' => \[/,/\],/s|DB_DATABASE|AZURE_MYSQL_DBNAME|g' config/database.php
          # Replace DB_USERNAME with AZURE_MYSQL_USERNAME for the MySQL configuration section
          sed -i '/\'mysql\' => \[/,/\],/s|DB_USERNAME|AZURE_MYSQL_USERNAME|g' config/database.php
          # Replace DB_PASSWORD with AZURE_MYSQL_PASSWORD for the MySQL configuration section
          sed -i '/\'mysql\' => \[/,/\],/s|DB_PASSWORD|AZURE_MYSQL_PASSWORD|g' config/database.php
          echo "Replaced DB_* with AZURE_MYSQL_* variables in the MySQL configuration section of config/database.php"

      - name: Run Laravel Migrations
        run: |
          az webapp ssh --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group YourResourceGroup --command "
          cd /home/site/wwwroot &&
          php artisan migrate --force"
