name: Build and deploy Laravel app to Azure Web App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: mylaravelapp        # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'         # Path to your Laravel project
  PHP_VERSION: '8.2'                     # PHP version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, pdo, bcmath, intl

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Build front-end assets
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: |
          npm install
          npm run build --production

      - name: Download SSL CA file
        run: |
          wget -O ./storage/ssl/DigiCertGlobalRootCA.crt.pem https://dl.cacerts.digicert.com/DigiCertGlobalRootCA.crt.pem

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: laravel-app
          path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: laravel-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
