name: Build and Push Docker Image with Dynamic Tag

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Fetch tags to extract the latest Git tag
      - name: Fetch all tags
        run: git fetch --tags

      # Extract the latest Git tag or fallback to "latest"
      - name: Get the latest Git tag
        id: git_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 --match "v*" || echo "latest")
          echo "TAG=$TAG" >> $GITHUB_ENV
        env:
          GITHUB_ENV: ${{ env.GITHUB_ENV }}

      # Log in to Docker registry
      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.REGISTRY_URL || 'docker.io' }}

      # Use Docker Compose to build and push with dynamic tag
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ env.TAG }}
          docker-compose -f docker-compose.yml build --build-arg TAG=$IMAGE_TAG
          docker-compose -f docker-compose.yml push
