name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment file
        run: mv .env.example .env
        
      - name: Replace environment variables
        run: |
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env && \
          sed -i 's/# DB_HOST=.*/DB_HOST=db/' .env && \
          sed -i 's/# DB_PORT=.*/DB_PORT=3306/' .env && \
          sed -i 's/# DB_DATABASE=.*/DB_DATABASE=laravel/' .env && \
          sed -i 's/# DB_USERNAME=.*/DB_USERNAME=laravel/' .env && \
          sed -i 's/# DB_PASSWORD=.*/DB_PASSWORD=1234/' .env


      # Set up Docker Buildx
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Extract the Git tag
      - name: Extract Git tag
        id: get_tag
        run: |
          tag=${GITHUB_REF#refs/*/} # Remove "refs/tags/" prefix to get the tag name
          echo "tag=${tag}" >> $GITHUB_ENV

      # Replace the image tag in docker-compose.yml
      - name: Replace image tag in docker-compose
        run: |
          sed -i "s|image:.*|image: johnverz7/laravel-app:${tag}|" docker-compose.yml

      # Log in to DockerHub
      - name: Log in to DockerHub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker compose build
          docker compose push
        env:
          tag: ${{ env.tag }}
